export const FONTS = [
    { name: 'Albert Sans', label: 'Albert Sans', premium: false },
    { name: 'Barlow Condensed', label: 'Barlow Condensed', premium: true },
    { name: 'Bebas Neue', label: 'Bebas Neue', premium: true },
    { name: 'Cinzel', label: 'Cinzel', premium: true },
    { name: 'Cormorant Garamond', label: 'Cormorant Garamond', premium: true },
    { name: 'DM Sans', label: 'DM Sans', premium: false },
    { name: 'DM Serif Display', label: 'DM Serif Display', premium: true },
    { name: 'Exo 2', label: 'Exo 2', premium: true },
    { name: 'Fira Code', label: 'Fira Code', premium: true },
    { name: 'Inter', label: 'Inter', premium: false },
    { name: 'JetBrains Mono', label: 'JetBrains Mono', premium: true },
    { name: 'Josefin Sans', label: 'Josefin Sans', premium: true },
    { name: 'Kanit', label: 'Kanit', premium: false },
    { name: 'Karla', label: 'Karla', premium: false },
    { name: 'Lato', label: 'Lato', premium: false },
    { name: 'Lora', label: 'Lora', premium: true },
    { name: 'Manrope', label: 'Manrope', premium: false },
    { name: 'Merriweather', label: 'Merriweather', premium: true },
    { name: 'Montserrat', label: 'Montserrat', premium: false },
    { name: 'Mulish', label: 'Mulish', premium: false },
    { name: 'Noto Sans JP', label: 'Noto Sans JP', premium: true },
    { name: 'Nunito', label: 'Nunito', premium: true },
    { name: 'Open Sans', label: 'Open Sans', premium: false },
    { name: 'Orbitron', label: 'Orbitron', premium: true },
    { name: 'Oswald', label: 'Oswald', premium: true },
    { name: 'Oxanium', label: 'Oxanium', premium: false },
    { name: 'Playfair Display', label: 'Playfair Display', premium: true },
    { name: 'Poppins', label: 'Poppins', premium: true },
    { name: 'Quicksand', label: 'Quicksand', premium: true },
    { name: 'Raleway', label: 'Raleway', premium: false },
    { name: 'Righteous', label: 'Righteous', premium: true },
    { name: 'Roboto', label: 'Roboto', premium: false },
    { name: 'Russo One', label: 'Russo One', premium: true },
    { name: 'Shantell Sans', label: 'Shantell Sans', premium: true },
    { name: 'Space Grotesk', label: 'Space Grotesk', premium: true },
    { name: 'Syne', label: 'Syne', premium: true },
    { name: 'Ubuntu', label: 'Ubuntu', premium: false }, 
    { name: 'Work Sans', label: 'Work Sans', premium: false },
]