export const THEME_PRESETS = {
    arcade: {
        label: 'Arcade',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Righteous',
        username_style: { size: 'medium', textColor: 'FF80FF' },
        bio_style: { textColor: 'CE93D8' },
        wallpaper_style: { backgroundColor: '1A0A1A' },
        button_style: { variant: 'filled', backgroundColor: 'E040FB', textColor: '1A0A1A', borderRadius: 'rounded-xl' },
    },
    carbon: {
        label: 'Carbon',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Exo 2',
        username_style: { size: 'normal', textColor: 'FFFFFF' },
        bio_style: { textColor: '9E9E9E' },
        wallpaper_style: { backgroundColor: '111111' },
        button_style: { variant: 'outlined', backgroundColor: 'FFFFFF', textColor: 'FFFFFF', borderRadius: 'rounded-md' },
    },
    cat: {
        label: 'Cat',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Shantell Sans',
        username_style: { size: 'normal', textColor: '2D2D2D' },
        bio_style: { textColor: '757575' },
        wallpaper_style: { backgroundColor: 'F5F0FF' },
        button_style: { variant: 'filled', backgroundColor: '9C89CC', textColor: 'FFFFFF', borderRadius: 'rounded-full' },
    },
    charmi: {
        label: 'Charmi',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Noto Sans JP',
        username_style: { size: 'medium', textColor: 'F5D98B', },
        bio_style: { textColor: 'C9A84C', },
        wallpaper_style: { backgroundColor: '0A0800', },
        button_style: { variant: 'filled', backgroundColor: 'D4AF37', textColor: '0A0800', borderRadius: 'rounded-lg', },
    },
    coffee: {
        label: 'Coffee',
        font_family: 'Inter',
        username_style: { size: 'normal', textColor: '1F2937', },
        bio_style: { textColor: '4B5563', },
        wallpaper_style: { backgroundColor: 'F5F1EE', },
        button_style: { variant: 'outlined', backgroundColor: 'A16207', textColor: '3F2A1D', borderRadius: 'rounded-full', },
    },
    cosy: {
        label: 'Cosy',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Quicksand',
        username_style: { size: 'normal', textColor: '5C3D2E' },
        bio_style: { textColor: '8B6355' },
        wallpaper_style: { backgroundColor: 'FDF0E8' },
        button_style: { variant: 'filled', backgroundColor: 'E8A598', textColor: 'FFFFFF', borderRadius: 'rounded-full' },
    },
    dark: {
        label: 'Dark',
        font_family: 'Inter',
        username_style: { size: 'normal', textColor: 'FFFFFF', },
        bio_style: { textColor: 'D4D4D8', },
        wallpaper_style: { backgroundColor: '18181B', },
        button_style: { variant: 'filled', backgroundColor: 'FFFFFF', textColor: '000000', borderRadius: 'rounded-lg', },
    },
    dark_esport: {
        label: 'Dark Esport',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Russo One',
        username_style: { size: 'medium', textColor: 'F5A623' },
        bio_style: { textColor: 'B8860B' },
        wallpaper_style: { backgroundColor: '0A0A0A' },
        button_style: { variant: 'filled', backgroundColor: 'F5A623', textColor: '0A0A0A', borderRadius: 'rounded-none' },
    },
    emerald: {
        label: 'Emerald',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Josefin Sans',
        username_style: { size: 'medium', textColor: '00E676' },
        bio_style: { textColor: '69F0AE' },
        wallpaper_style: { backgroundColor: '001A0A' },
        button_style: { variant: 'filled', backgroundColor: '00C853', textColor: '001A0A', borderRadius: 'rounded-lg' },
    },
    horror: {
        label: 'Horror',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Oswald',
        username_style: { size: 'medium', textColor: 'FF1744' },
        bio_style: { textColor: '8B0000' },
        wallpaper_style: { backgroundColor: '0A0000' },
        button_style: { variant: 'outlined', backgroundColor: 'FF1744', textColor: 'FF1744', borderRadius: 'rounded-none' },
    },
    ivory: {
        label: 'Ivory',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Playfair Display',
        username_style: { size: 'normal', textColor: '1A1A1A' },
        bio_style: { textColor: '4A4A4A' },
        wallpaper_style: { backgroundColor: 'FAF7F2' },
        button_style: { variant: 'filled', backgroundColor: '1A1A1A', textColor: 'FAF7F2', borderRadius: 'rounded-lg' },
    },
    kawaii: {
        label: 'Kawaii',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Nunito',
        username_style: { size: 'normal', textColor: 'FF6B9D' },
        bio_style: { textColor: 'FF8FB1' },
        wallpaper_style: { backgroundColor: 'FFF0F5' },
        button_style: { variant: 'filled', backgroundColor: 'FF6B9D', textColor: 'FFFFFF', borderRadius: 'rounded-full' },
    },
    light: {
        label: 'Light',
        font_family: 'Inter',
        username_style: { size: 'normal', textColor: '111827', },
        bio_style: { textColor: '374151', },
        wallpaper_style: { backgroundColor: 'ECEEF1', },
        button_style: { variant: 'filled', backgroundColor: 'FFFFFF', textColor: '111827', borderRadius: 'rounded-lg', },
    },
    manga: {
        label: 'Manga',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Noto Sans JP',
        username_style: { size: 'medium', textColor: '1A1A2E' },
        bio_style: { textColor: '4A4A6A' },
        wallpaper_style: { backgroundColor: 'F0F0F0' },
        button_style: { variant: 'filled', backgroundColor: '1A1A2E', textColor: 'FFFFFF', borderRadius: 'rounded-none' },
    },
    neon_grid: {
        label: 'Neon Grid',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Orbitron',
        username_style: { size: 'medium', textColor: '00F5FF' },
        bio_style: { textColor: '7ECFD4' },
        wallpaper_style: { backgroundColor: '0D0D1A' },
        button_style: { variant: 'filled', backgroundColor: '00F5FF', textColor: '0D0D1A', borderRadius: 'rounded-lg' },
    },
    rpg: {
        label: 'RPG',
        premium: true,
        featureKey: 'premium_theme',
        font_family: 'Cinzel',
        username_style: { size: 'medium', textColor: 'FFD700' },
        bio_style: { textColor: 'C8A951' },
        wallpaper_style: { backgroundColor: '0E0B16' },
        button_style: { variant: 'outlined', backgroundColor: 'FFD700', textColor: 'FFD700', borderRadius: 'rounded-sm' },
    },
    twitch: {
        label: 'Twitch',
        font_family: 'Manrope',
        username_style: { size: 'medium', textColor: 'FFFFFF', },
        bio_style: { textColor: 'B39DDB', },
        wallpaper_style: { backgroundColor: '0F0B1F', },
        button_style: { variant: 'filled', backgroundColor: '7C4DFF', textColor: 'FFFFFF', borderRadius: 'rounded-xl', },
    },
    urban: {
        label: 'Urban',
        font_family: 'DM Sans',
        username_style: { size: 'normal', textColor: 'FFFFFF' },
        bio_style: { textColor: 'B0BEC5' },
        wallpaper_style: { backgroundColor: '1C1C1E' },
        button_style: { variant: 'filled', backgroundColor: '0A84FF', textColor: 'FFFFFF', borderRadius: 'rounded-xl' },
    },
}
